(()=>{
'use strict';
const STORE='BilibiliExtraV1';
const $=s=>document.querySelector(s);
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(STORE+':'+k))??d}catch{return d}};
const put=(k,v)=>localStorage.setItem(STORE+':'+k,JSON.stringify(v));
let meta={},favorites=new Set(get('favorites',[])),playlists=get('playlists',{}),recent=get('recent',[]),theme=get('theme','amoled'),crossfade=get('crossfade',false),gapless=get('gapless',true),sleepAt=0;
const audio=document.getElementById('audio');
const cover=document.getElementById('cover');
const title=document.getElementById('title');
const artist=document.getElementById('artist');
const songs=document.getElementById('songs');
const search=document.getElementById('searchInput');
const player=document.querySelector('.player');
function save(){put('favorites',[...favorites]);put('playlists',playlists);put('recent',recent);put('theme',theme);put('crossfade',crossfade);put('gapless',gapless)}
function esc(v){const d=document.createElement('div');d.textContent=v||'';return d.innerHTML}
function art(name,artist){const a=(name||'BILIBILI MUSIC').slice(0,22);const b=(artist||'LOCAL MUSIC').slice(0,18);const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="800" height="800"><rect width="800" height="800" fill="#090909"/><circle cx="620" cy="150" r="230" fill="#c2185b"/><circle cx="140" cy="650" r="260" fill="#2b2b2b"/><text x="45" y="610" fill="#fff" font-size="42" font-family="monospace">${a.replace(/[<&>]/g,'')}</text><text x="45" y="665" fill="#aaa" font-size="23" font-family="monospace">${b.replace(/[<&>]/g,'')}</text><text x="45" y="730" fill="#777" font-size="17" font-family="monospace">BILIBILI MUSIC</text></svg>`;return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
function toast(t){let x=document.getElementById('bxToast');if(!x){x=document.createElement('div');x.id='bxToast';x.style='position:fixed;left:50%;bottom:86px;transform:translateX(-50%);background:#fff;color:#000;padding:9px 13px;border-radius:12px;font:10px monospace;z-index:20000;transition:.2s;opacity:0';document.body.appendChild(x)}x.textContent=t;x.style.opacity='1';clearTimeout(x.t);x.t=setTimeout(()=>x.style.opacity='0',1500)}
function modal(head,body){let m=document.getElementById('bxModal');if(!m){m=document.createElement('div');m.id='bxModal';m.innerHTML='<div id="bxSheet"></div>';m.onclick=e=>{if(e.target===m)m.remove()};document.body.appendChild(m)}const s=m.firstElementChild;s.innerHTML=`<h2>${esc(head)} <button id="bxClose">×</button></h2>${body}`;m.querySelector('#bxClose').onclick=()=>m.remove();return s}
const style=document.createElement('style');style.textContent=`.song{position:relative;min-height:62px;padding-left:6px!important}.bxSongArt{width:48px;height:48px;border-radius:12px;object-fit:cover;background:#151515;flex:none;border:1px solid #292929}.song.playing .bxSongArt{border-color:#c2185b}.songCardMeta{display:flex;align-items:center;gap:7px;margin-top:4px}.songCardMeta .songSize{margin-top:0}.bxMore{width:30px!important;height:34px!important;flex:none!important;padding:0!important;text-align:center!important;font-size:16px!important}.bar{touch-action:none;position:relative}.fill{pointer-events:none}`;style.textContent+=`#bxModal{position:fixed;inset:0;background:rgba(0,0,0,.74);backdrop-filter:blur(9px);z-index:18000;display:flex;align-items:flex-end;justify-content:center}#bxSheet{width:min(430px,100%);max-height:84vh;overflow:auto;background:#0b0b0b;color:#fff;border:1px solid #333;border-radius:24px 24px 0 0;padding:18px;font-family:"Courier New",monospace}#bxSheet h2{font-size:15px;margin-bottom:12px}#bxSheet h2 button{float:right;border:0;background:none;color:#fff;font-size:20px}#bxSheet button,#bxSheet input{display:block;width:100%;border:1px solid #333;background:#111;color:#fff;border-radius:12px;padding:11px;margin:7px 0;font:10px monospace;text-align:left}#bxSheet .bxgrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}#bxSheet .bxmuted{color:#777;font-size:9px}.bxMini{position:fixed;left:50%;bottom:12px;transform:translateX(-50%);width:min(405px,calc(100vw - 28px));display:flex;align-items:center;gap:9px;padding:8px 10px;background:rgba(10,10,10,.96);border:1px solid #333;border-radius:18px;z-index:9000;box-shadow:0 12px 40px #000}.bxMini img{width:38px;height:38px;border-radius:10px;object-fit:cover}.bxMini div{flex:1;min-width:0}.bxMini b,.bxMini small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.bxMini b{font-size:10px}.bxMini small{font-size:8px;color:#777;margin-top:3px}.bxMini button{width:30px;border:0;background:none;color:#fff;font-size:16px}.bxTools{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.bxTools button{border:1px solid #292929;background:#090909;color:#fff;border-radius:12px;height:40px;font:9px monospace}.bxFav{color:#c2185b!important}`;document.head.appendChild(style);
function capture(items){(items||[]).forEach(x=>{meta[String(x.id)]={...meta[String(x.id)],...x,art:x.art||art(x.name,x.artist)};});put('meta',meta)}
meta=get('meta',{});
const oldScan=window.onNativeMusicScan;
window.onNativeMusicScan=function(items){capture(items);if(oldScan)oldScan(items);setTimeout(syncMeta,200)};
function syncMeta(){document.querySelectorAll('.song').forEach(row=>{const n=row.querySelector('.songName')?.textContent?.trim();const found=Object.values(meta).find(x=>(x.name||'')===n);if(found){row.dataset.mid=found.id;let img=row.querySelector('.bxSongArt');if(!img){img=document.createElement('img');img.className='bxSongArt';img.alt='';row.insertBefore(img,row.firstElementChild)}img.src=found.art||art(found.name,found.artist);let sm=row.querySelector('.songSize');if(sm)sm.textContent=`${found.artist||'LOCAL MUSIC'} • ${found.album||'UNKNOWN ALBUM'} • ${found.folder||'Music'}`;let more=row.querySelector('.bxMore');if(!more){more=document.createElement('button');more.className='bxMore';more.type='button';more.textContent='⋮';more.title='Song options';row.appendChild(more)}}});if(title?.textContent&&title.textContent!=='NO SONG'){const n=title.textContent.trim();const a=artist?.textContent?.trim();const found=Object.values(meta).find(x=>(x.name||'').toUpperCase()===n&&(!a||x.artist===a));if(found){cover.src=found.art||art(found.name,found.artist)}}}
function songObjects(){return [...document.querySelectorAll('.song')].map((row,i)=>{const n=row.querySelector('.songName')?.textContent?.trim()||'';const sm=row.querySelector('.songSize')?.textContent?.trim()||'';const found=Object.values(meta).find(x=>(x.name||'')===n)||{};return {id:String(found.id||'manual-'+n),name:n,artist:found.artist||sm.split(' • ')[0]||'LOCAL MUSIC',album:found.album||sm.split(' • ')[1]||'UNKNOWN ALBUM',folder:found.folder||sm.split(' • ')[2]||'Music',row,index:i,art:found.art||art(n,found.artist)}})}
function selectedSong(){const t=title?.textContent?.trim()||'';return songObjects().find(s=>(s.name||'').toUpperCase()===t)||songObjects().find(s=>s.row.classList.contains('playing'))}
function mini(){let m=document.getElementById('bxMini');if(!m){m=document.createElement('div');m.id='bxMini';m.className='bxMini';m.innerHTML='<img id="bxMiniArt"><div><b id="bxMiniTitle">NO SONG</b><small id="bxMiniArtist">BILIBILI</small></div><button id="bxPrev">◀</button><button id="bxMiniPlay">▶</button><button id="bxNext">▶</button>';document.body.appendChild(m);m.querySelector('#bxMiniPlay').onclick=()=>document.getElementById('play')?.click();m.querySelector('#bxPrev').onclick=()=>window.previousSong?.();m.querySelector('#bxNext').onclick=()=>window.nextSong?.()}}
function updateMini(){mini();const s=selectedSong();if(!s)return;document.getElementById('bxMiniArt').src=s.art;document.getElementById('bxMiniTitle').textContent=s.name;document.getElementById('bxMiniArtist').textContent=s.artist||'LOCAL MUSIC'}
function details(s){modal('SONG DETAILS',`<div class="bxmuted">Metadata from the device/library</div><button>Title — ${esc(s.name)}</button><button>Artist — ${esc(s.artist)}</button><button>Album — ${esc(s.album)}</button><button>Folder — ${esc(s.folder)}</button><button>Format — ${esc(meta[s.id]?.type||'audio')}</button><button>Size — ${esc(meta[s.id]?.size||'LOCAL MUSIC')}</button><button>Duration — ${esc(meta[s.id]?.duration?fmt(meta[s.id].duration/1000):'Not indexed')}</button>`)}
function fmt(s){s=Number(s)||0;return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')}
function menu(s){const names=Object.keys(playlists);modal('SONG OPTIONS',`<button id="bxFav">${favorites.has(s.id)?'Remove from favorites':'Add to favorites'}</button><button id="bxDetails">Song details</button><button id="bxLyrics">Lyrics</button>${names.map(n=>`<button data-pl="${esc(n)}">Add to ${esc(n)}</button>`).join('')}<button id="bxRemove">Remove from favorites/list</button>`);document.getElementById('bxFav').onclick=()=>{favorites.has(s.id)?favorites.delete(s.id):favorites.add(s.id);save();toast(favorites.has(s.id)?'Added to favorites':'Removed from favorites');document.getElementById('bxModal')?.remove()};document.getElementById('bxDetails').onclick=()=>details(s);document.getElementById('bxLyrics').onclick=()=>lyrics(s);document.getElementById('bxRemove').onclick=()=>{s.row?.querySelector('.delete')?.click();document.getElementById('bxModal')?.remove()};document.querySelectorAll('[data-pl]').forEach(b=>b.onclick=()=>{const n=b.dataset.pl;playlists[n]=[...(playlists[n]||[]),s.id];playlists[n]=[...new Set(playlists[n])];save();toast('Added to playlist');document.getElementById('bxModal')?.remove()})}
function lyrics(s){modal('LYRICS',`<div class="bxmuted">No synchronized lyrics are embedded in this local track.</div><button>${esc(s.name)}</button><button>${esc(s.artist)}</button>`)}
function library(){const list=songObjects();modal('LIBRARY',`<div class="bxTools"><button id="bxAll">ALL</button><button id="bxFavs">FAVORITES</button><button id="bxFolders">FOLDERS</button><button id="bxArtists">ARTISTS</button><button id="bxAlbums">ALBUMS</button><button id="bxRecent">RECENT</button></div><div id="bxList"></div>`);const out=$('#bxList');const render=a=>out.innerHTML=a.map(s=>`<button data-open="${esc(s.name)}">${esc(s.name)}<span class="bxmuted"> • ${esc(s.artist)} • ${esc(s.album)}</span></button>`).join('')||'<div class="bxmuted">NO MUSIC</div>';render(list);document.getElementById('bxAll').onclick=()=>render(list);document.getElementById('bxFavs').onclick=()=>render(list.filter(s=>favorites.has(s.id)));document.getElementById('bxRecent').onclick=()=>render(list.filter(s=>recent.includes(s.id)));document.getElementById('bxFolders').onclick=()=>group('folder',out);document.getElementById('bxArtists').onclick=()=>group('artist',out);document.getElementById('bxAlbums').onclick=()=>group('album',out);out.onclick=e=>{const b=e.target.closest('[data-open]');if(!b)return;const s=list.find(x=>x.name===b.dataset.open);s?.row.click();document.getElementById('bxModal')?.remove()}}
function group(k,out){const vals=[...new Set(songObjects().map(s=>s[k]||'Unknown'))];out.innerHTML=vals.map(v=>`<button data-group="${esc(v)}">${esc(v)}</button>`).join('')||'<div class="bxmuted">EMPTY</div>';out.onclick=e=>{const b=e.target.closest('[data-group]');if(!b)return;const v=b.dataset.group;const list=songObjects().filter(s=>(s[k]||'Unknown')===v);out.innerHTML=list.map(s=>`<button data-open="${esc(s.name)}">${esc(s.name)}<span class="bxmuted"> • ${esc(s.artist)}</span></button>`).join('')||'<div class="bxmuted">EMPTY</div>';out.onclick=ev=>{const q=ev.target.closest('[data-open]');if(!q)return;const s=list.find(x=>x.name===q.dataset.open);s?.row.click();document.getElementById('bxModal')?.remove()}}}
function playlistsUI(){const names=Object.keys(playlists);modal('PLAYLISTS',`<input id="bxNew" placeholder="New playlist name"><button id="bxCreate">+ CREATE PLAYLIST</button><div id="bxPL">${names.map(n=>`<button data-pln="${esc(n)}">${esc(n)} (${playlists[n].length})</button>`).join('')||'<div class="bxmuted">NO PLAYLISTS</div>'}</div>`);document.getElementById('bxCreate').onclick=()=>{const n=document.getElementById('bxNew').value.trim();if(!n)return;playlists[n]=[];save();playlistsUI()};document.querySelectorAll('[data-pln]').forEach(b=>b.onclick=()=>playlistView(b.dataset.pln))}
function playlistView(n){const list=songObjects().filter(s=>(playlists[n]||[]).includes(s.id));modal(n,list.map(s=>`<button data-open="${esc(s.name)}">${esc(s.name)} • ${esc(s.artist)}</button>`).join('')||'<div class="bxmuted">NO SONGS</div>');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const s=list.find(x=>x.name===b.dataset.open);s?.row.click();document.getElementById('bxModal')?.remove()})}
function queueUI(){const list=songObjects();modal('QUEUE',`<div class="bxmuted">Queue follows the current library order. Use Shuffle/Next for playback order.</div>${list.map(s=>`<button data-open="${esc(s.name)}">${esc(s.name)} • ${esc(s.artist)}</button>`).join('')}`);document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const s=list.find(x=>x.name===b.dataset.open);s?.row.click();document.getElementById('bxModal')?.remove()})}
function recentUI(){const list=songObjects().filter(s=>recent.includes(s.id));modal('RECENTLY PLAYED / ADDED',list.map(s=>`<button data-open="${esc(s.name)}">${esc(s.name)} • ${esc(s.artist)}</button>`).join('')||'<div class="bxmuted">NO RECENT TRACKS</div>');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const s=list.find(x=>x.name===b.dataset.open);s?.row.click();document.getElementById('bxModal')?.remove()})}
function settings(){modal('SETTINGS',`<button id="bxTheme">Theme: ${theme.toUpperCase()}</button><button id="bxCross">Crossfade: ${crossfade?'ON':'OFF'}</button><button id="bxGap">Gapless playback: ${gapless?'ON':'OFF'}</button><button id="bxSleep">Sleep timer</button><button id="bxFavList">Favorites (${favorites.size})</button>`);document.getElementById('bxTheme').onclick=()=>{theme=theme==='amoled'?'dark':theme==='dark'?'light':'amoled';document.body.dataset.bxTheme=theme;save();settings()};document.getElementById('bxCross').onclick=()=>{crossfade=!crossfade;save();toast(crossfade?'Crossfade on':'Crossfade off');settings()};document.getElementById('bxGap').onclick=()=>{gapless=!gapless;save();toast(gapless?'Gapless mode on':'Gapless mode off');settings()};document.getElementById('bxSleep').onclick=sleep;document.getElementById('bxFavList').onclick=()=>{const list=songObjects().filter(s=>favorites.has(s.id));modal('FAVORITES',list.map(s=>`<button data-open="${esc(s.name)}">♥ ${esc(s.name)}</button>`).join('')||'<div class="bxmuted">NO FAVORITES</div>');document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const s=list.find(x=>x.name===b.dataset.open);s?.row.click();document.getElementById('bxModal')?.remove()})}}
function sleep(){modal('SLEEP TIMER',`<button onclick="window.bxSleep(15)">15 MINUTES</button><button onclick="window.bxSleep(30)">30 MINUTES</button><button onclick="window.bxSleep(60)">60 MINUTES</button><button onclick="window.bxSleep(0)">OFF</button>`)}
window.bxSleep=m=>{if(sleepAt)clearTimeout(sleepAt);if(m){sleepAt=setTimeout(()=>{audio.pause();toast('Sleep timer finished')},m*60000);toast('Sleep timer: '+m+' min')}document.getElementById('bxModal')?.remove()};
function addTools(){const top=document.querySelector('.top');if(!top)return;const b=document.createElement('div');b.className='bxTools';b.innerHTML='<button id="bxLibrary">LIBRARY</button><button id="bxQueue">QUEUE</button><button id="bxPlaylists">PLAYLISTS</button><button id="bxSettings">SETTINGS</button>';top.parentNode.insertBefore(b,document.querySelector('.cover'));b.querySelector('#bxLibrary').onclick=library;b.querySelector('#bxQueue').onclick=queueUI;b.querySelector('#bxPlaylists').onclick=playlistsUI;b.querySelector('#bxSettings').onclick=settings}
function patchSeek(){const bar=document.getElementById('bar'),audio=document.getElementById('audio');if(!bar||!audio)return;const seek=e=>{if(!audio.duration)return;const r=bar.getBoundingClientRect();const x=e.touches?e.touches[0].clientX:e.clientX;audio.currentTime=Math.max(0,Math.min(1,(x-r.left)/r.width))*audio.duration};bar.addEventListener('pointerdown',e=>{e.preventDefault();seek(e)});bar.addEventListener('touchstart',e=>{e.preventDefault();seek(e)},{passive:false});bar.addEventListener('touchmove',e=>{e.preventDefault();seek(e)},{passive:false})}
function patchSearch(){if(!search)return;const old=search.oninput;search.oninput=()=>{old?.call(search);const q=search.value.toLowerCase().trim();document.querySelectorAll('.song').forEach(r=>{const t=(r.textContent||'').toLowerCase();r.style.display=!q||t.includes(q)?'flex':'none'})}}
function mediaSession(){if(!('mediaSession'in navigator))return;const set=()=>{const s=selectedSong();if(!s)return;navigator.mediaSession.metadata=new MediaMetadata({title:s.name,artist:s.artist||'LOCAL MUSIC',album:s.album||'Bilibili Music',artwork:[{src:s.art,sizes:'512x512',type:'image/svg+xml'}]});navigator.mediaSession.setActionHandler('play',()=>audio.play());navigator.mediaSession.setActionHandler('pause',()=>audio.pause());navigator.mediaSession.setActionHandler('previoustrack',()=>window.previousSong?.());navigator.mediaSession.setActionHandler('nexttrack',()=>window.nextSong?.());navigator.mediaSession.setActionHandler('seekbackward',()=>audio.currentTime=Math.max(0,audio.currentTime-10));navigator.mediaSession.setActionHandler('seekforward',()=>audio.currentTime=Math.min(audio.duration,audio.currentTime+10))};set();setInterval(set,1200)}
function watch(){let last='';setInterval(()=>{syncMeta();updateMini();const cur=title?.textContent||'';if(cur!==last){last=cur;const s=selectedSong();if(s){recent=[s.id,...recent.filter(x=>x!==s.id)].slice(0,30);save();if(s.art)cover.src=s.art}}if(audio.paused===false&&sleepAt&&Date.now()>sleepAt){audio.pause()}},800)}
function boot(){addTools();patchSeek();patchSearch();mediaSession();watch();mini();document.body.dataset.bxTheme=theme;syncMeta();songs?.addEventListener('click',e=>{const row=e.target.closest('.song');if(!row)return;setTimeout(()=>{const s=selectedSong();if(s)recent=[s.id,...recent.filter(x=>x!==s.id)].slice(0,30);save();updateMini();syncMeta()},250);if(e.target.closest('.delete'))return;if(e.target.closest('.songMore')){const s=songObjects().find(x=>x.row===row);if(s)menu(s)}});document.getElementById('settings')?.addEventListener('click',settings)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
