(()=>{'use strict';
const audio=document.getElementById('audio'),bar=document.getElementById('bar'),fill=document.getElementById('fill'),cur=document.getElementById('current'),dur=document.getElementById('duration'),cover=document.getElementById('cover'),title=document.getElementById('title'),artist=document.getElementById('artist'),songs=document.getElementById('songs');if(!audio||!bar||!fill||!songs)return;
const K='BilibiliMusicNativeMetaV3';let meta={};try{meta=JSON.parse(localStorage.getItem(K)||'{}')}catch(e){}
const tm=v=>Number.isFinite(v)&&v>=0?Math.floor(v/60)+':'+String(Math.floor(v%60)).padStart(2,'0'):'0:00';
function ph(n,a){n=String(n||'BILIBILI MUSIC').slice(0,22).replace(/[<&>]/g,'');a=String(a||'LOCAL MUSIC').slice(0,18).replace(/[<&>]/g,'');return'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="700" height="700"><rect width="700" height="700" fill="#101010"/><circle cx="560" cy="130" r="250" fill="#c2185b"/><circle cx="100" cy="620" r="250" fill="#292929"/><text x="35" y="535" fill="white" font-size="38" font-family="monospace">${n}</text><text x="35" y="590" fill="#aaa" font-size="20" font-family="monospace">${a}</text></svg>`)}
function rm(r){const n=r.querySelector('.songName')?.textContent?.trim()||'';return Object.values(meta).find(x=>(x.name||'').toLowerCase()===n.toLowerCase())||{name:n,artist:r.querySelector('.songSize')?.textContent||'LOCAL MUSIC'}}
function art(m){return m?.albumId!=null?'https://appassets.androidplatform.net/albumart/'+encodeURIComponent(String(m.albumId)):m?.art||ph(m?.name,m?.artist)}
function decorate(){songs.querySelectorAll('.song').forEach(r=>{if(r.classList.contains('bxCardReady'))return;const i=r.querySelector('.songInfo');if(!i)return;const m=rm(r),im=document.createElement('img');im.className='bxCardArt';im.src=art(m);im.onerror=()=>im.src=ph(m.name,m.artist);r.insertBefore(im,i);r.classList.add('bxCardReady')});const a=songs.querySelector('.song.playing');if(a&&cover){const m=rm(a);cover.src=art(m);if(title&&m.name)title.textContent=m.name;if(artist&&m.artist)artist.textContent=m.artist}}
const st=document.createElement('style');st.textContent='.song{position:relative;min-height:66px}.bxCardArt{width:52px;height:52px;flex:none;border-radius:12px;object-fit:cover;background:#111;border:1px solid #292929;display:block}.bar{position:relative;min-height:16px;padding:4px 0;touch-action:none}.fill{pointer-events:none}';document.head.appendChild(st);
function seek(x){if(!Number.isFinite(audio.duration)||audio.duration<=0)return;const r=bar.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(1,(x-r.left)/r.width))*audio.duration}
let drag=false;bar.addEventListener('pointerdown',e=>{drag=true;bar.setPointerCapture?.(e.pointerId);seek(e.clientX);e.preventDefault()});bar.addEventListener('pointermove',e=>{if(drag){seek(e.clientX);e.preventDefault()}});bar.addEventListener('pointerup',e=>{if(drag){seek(e.clientX);drag=false}});bar.addEventListener('pointercancel',()=>drag=false);bar.addEventListener('click',e=>seek(e.clientX));
audio.addEventListener('timeupdate',()=>{if(!Number.isFinite(audio.duration)||audio.duration<=0)return;fill.style.width=(audio.currentTime/audio.duration*100)+'%';if(cur)cur.textContent=tm(audio.currentTime);if(dur)dur.textContent=tm(audio.duration)});audio.addEventListener('loadedmetadata',()=>{if(dur)dur.textContent=tm(audio.duration)});
const old=window.onNativeMusicScan;window.onNativeMusicScan=function(items){(items||[]).forEach(x=>meta[String(x.id)]=x);try{localStorage.setItem(K,JSON.stringify(meta))}catch(e){}if(typeof old==='function')old(items);setTimeout(decorate,100);setTimeout(decorate,800)};
songs.addEventListener('click',()=>setTimeout(decorate,100),true);new MutationObserver(decorate).observe(songs,{childList:true,subtree:true});setInterval(decorate,1200);decorate();
})();